# vim:set expandtab shiftwidth=4 filetype=yaml foldlevel=5:
# SPDX-License-Identifier: GPL-3.0-only

#
#
# ~chewygumxx/repo-tmpl.git
# ::: :/.github/workflows/sync-header-metadata.yaml
#
#

name: Sync Header Metadata

on:
    push:
        branches:
            - main
    pull_request:
    workflow_dispatch: {}

jobs:
    update:
        permissions:
            contents: write
        uses: chewygumxx/.github/.github/workflows/sync-header-metadata.yaml@v1
